### ISSUE TITLE
Application failed to start - Ubuntu 19.10/Wayland

### ISSUE THREAD

**Issue by ghost** [snapcrafters/mumble#10]
Hi. I'm unable to launch Mumble on Ubuntu 19.10, running in a Gnome 3 Wayland environment.
This is on a laptop with Intel iGPU, default drivers included with Ubuntu.

```
...$ sudo snap install mumble
mumble 1.3.0 from Snapcrafters installed
...$ mumble
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

**Comment by Krzmbrzl** [comment]
We just got a report that the snap package seems to have the same issue with Ubuntu 20.04. See https://github.com/mumble-voip/mumble/issues/4308 for details :point_up:

**Comment by vEpiphyte** [comment]
The snap package continues to have issues with Ubuntu 21.04 which ships with wayland by default.

**Comment by Krzmbrzl** [comment]
@vEpiphyte and what about the regular Mumble package from the Ubuntu repos?

**Comment by vEpiphyte** [comment]
@Krzmbrzl installing mumble from apt works fine
```
$ sudo apt list mumble
Listing... Done
mumble/hirsute,now 1.3.4-1 amd64 [installed]
```

**Comment by Krzmbrzl** [comment]
Okay then this continues to be a snap-only problem. Thanks for checking!

**Comment by q-wertz** [comment]
Any news on this?
