### ISSUE TITLE
[Feature Request] Regular updates (for dependencies)

### ISSUE THREAD

**Issue by toby63** [snapcrafters/mumble#11]
Hello,

first of all I want to thank you for providing this snap package :+1:.

**Problem:**
The implemented dependencies seem to be outdated in the stable branch.
For example:
Qt is version 5.9.5

**Solution:**
You could update this package more often (maybe every few months), to provide users with more recent dependency versions.

**Comment by popey** [comment]
Thanks for filing this issue.

What do you need from newer versions of Qt in this snap?

The mumble snap is built using an Ubuntu 18.04 system against the core18 snap. That means, the way it's currently written, it stages the various qt packages from the 18.04 Ubuntu archive as part of the build process. This is why you're seeing Qt 5.9.5, as that's what comes with Ubuntu 18.04 - as can be seen at https://packages.ubuntu.com/search?keywords=qttools5-dev-tools

While it would be technically possible to build all of the required Qt packages from source, that greatly lengthens build time, and is more moving parts to maintain. If someone wants to migrate this to an all-source built, and help maintain it, that'd be great, but I don't think it's super valuable.

We will, at some point migrate to being based off Ubuntu 20.04, which ships with Qt 5.12.8, but that won't happen for some months, I suspect.

**Comment by toby63** [comment]
@popey 
Thank you for the answer and the explanation :smiley:.

> What do you need from newer versions of Qt in this snap?

The overall idea is just to keep the dependency packages fairly up-to-date, as they are (obviously) bundled in this package.
Qt was just an example.

> The mumble snap is built using an Ubuntu 18.04

Ok, then everything is fine. I did not know that.

> We will, at some point migrate to being based off Ubuntu 20.04, which ships with Qt 5.12.8, but that won't happen for some months, I suspect.

Ok, I would highly appreciate that :+1:.
