### ISSUE TITLE
Audio Input Issues

### ISSUE THREAD

**Issue by ncc757** [snapcrafters/mumble#16]
The latest update appears to have broken audio Input. No microphone inputs work. Furthermore, under voice activity, the "Silence below" and "Speech Above" sliders do not adjust the Red Yellow, and Green areas anymore (See image).

![image](https://user-images.githubusercontent.com/47647314/95640716-adde5000-0a63-11eb-95f8-2d291586370b.png)

Additional info:
- This issue is present on both machines I tested it on, both using Ubuntu 20.04.
- Other applications recognize and hear microphone audio
- The apt-get version of mumble does not have this issue

**Comment by popey** [comment]
Sorry about that. Run `snap connect mumble:audio-record`

**Comment by raek** [comment]
I reported a bug at the Mumble Github issue tracker. (Didn't know about this bug ticket then.) https://github.com/mumble-voip/mumble/issues/4527

**Comment by ncc757** [comment]
> Sorry about that. Run `snap connect mumble:audio-record`

Fixes the issue
