### ISSUE TITLE
[Bug]: mumble plugin installation / loading fails

### ISSUE THREAD

**Issue by hbeni** [snapcrafters/mumble#23]
### What happened?

When trying to install the [fgcom-mumble](https://github.com/hbeni/fgcom-mumble) plugin, the sandboxing somehow prevents loading the Plugin shared object.
Mumble presents a (misleading) error about wrong plugin api, but the rootcause seems to be a problem with loading the shared object.

Even manually installing the (verified working) plugin.so by copying it into the plugins folder does not work.

### What should have happened?

Plugins should also work with the snap version.

### Details
- https://forum.flightgear.org/viewtopic.php?p=409953#p409953
- https://github.com/hbeni/fgcom-mumble

**Comment by merlijn-sebrechts** [comment]
I think I fixed this in https://github.com/snapcrafters/mumble/pull/24

It seemed the versions of mumble and supporting libraries were too old for the plugin.

You can test it out by running `sudo snap refresh mumble --channel=edge/fix-for-23`

**Comment by hbeni** [comment]
> I think I fixed this in #24
> [...]
> You can test it out by running `sudo snap refresh mumble --channel=edge/fix-for-23`


https://forum.flightgear.org/viewtopic.php?p=410153#p410153: jam007 confirms, it's working.
